language: node_js
node_js:
  - '4.1.2'

before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g bower karma grunt-cli jshint'
  - 'npm install' # install npm packages
  - 'bower install' # install bower packages

script:
  - 'grunt'

after_script:
  - 'grunt test'

